### ISSUE TITLE
Ver.10 doesn't work anymore

### ISSUE THREAD

**Issue by Moonlighteas** [torocc/KoikatuSaveDataEdit#6]
With latest update 0727 (game version 4.0) KoikatuSaveDataEdit ver.10 doesn't work anymore.

**Comment by madkiw** [comment]
Yeah, I'm getting this error

Traceback (most recent call last):
  File "gui.py", line 400, in <module>
  File "gui.py", line 388, in main
  File "gui.py", line 281, in __init__
  File "save_data.py", line 17, in __init__
  File "save_data.py", line 22, in _load
  File "save_data.py", line 42, in _read_utf8_string
ValueError: read length must be positive or -1
push Enter key

**Comment by kiletw** [comment]
I fix it https://github.com/kiletw/KoikatuSaveDataEdit/releases.

**Comment by Moonlighteas** [comment]
Very nice, save now loads but one problem, it can't load save with new personalities and can't read new personality cards properly

**Comment by jcbartlett** [comment]
@kiletw How do I get your version to work in English?
