### ISSUE TITLE
Ver.13 cannot save 

### ISSUE THREAD

**Issue by fao2fin** [torocc/KoikatuSaveDataEdit#7]
AttributeError: 'PropertyPanel' object has no attribute '_intellect'
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1702, in __call__
  File "gui.py", line 373, in save_and_quit
  File "gui.py", line 369, in save
  File "save_data.py", line 65, in save
  File "character.py", line 285, in save
  File "character.py", line 342, in _serialize
  File "character.py", line 177, in intelligence
KeyError: 'intelligence'

**Comment by kiletw** [comment]
Fix.
